enum A {
  GET_ALL_FIELDS,
  SET_ALL_FIELDS,
  SET_USER_PROFILE,
  SET_PERMISSIONS,
  SET_LICENSE,
  SET_AUTH,
  SET_CLIENT_AUTH,
  SET_OTP_AUTH,
  SET_PAGINATION,
  SET_TOTAL_PAGES,
  SET_LIMIT_DOCUMENT,
  //
  SET_DOCUMENT_SEARCH_DATA,
  //
  SET_MEMO_SEARCH_DATA,
  //EMAIL,
  SEND_EMAIL_HOURLY_ACCESS,
}

export default A;
